# Generated by Django 4.1.2 on 2022-10-18 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sealert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selinux_digest', models.CharField(max_length=200)),
                ('initialdetected', models.DateTimeField()),
                ('lastdetected', models.DateTimeField()),
                ('description', models.CharField(max_length=4096)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=200)),
                ('SEstatus', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='sealertonserver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('detected', models.DateTimeField()),
                ('status', models.CharField(max_length=200)),
                ('hostid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.server')),
                ('sealertid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.sealert')),
            ],
        ),
    ]
